Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,7 +42,7 @@ jobs:
       run: |
         eval $(ssh-agent -s)
         ssh-add -l
-        ssh -v root@${{ secrets.SERVER_IP }} exit
+        ssh -v -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} 'echo "SSH connection successful"'
 
     - name: Deploy with PM2
       run: |
@@ -55,7 +55,7 @@ jobs:
       run: |
         eval $(ssh-agent -s)
         ssh-add - <<< "${{ secrets.SERVER_SSH_KEY }}"
-        ssh root@${{ secrets.SERVER_IP }} 'pm2 list'
+        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} 'pm2 list'
 
     - name: Debug if failed
       if: failure()
@@ -63,4 +63,4 @@ jobs:
         eval $(ssh-agent -s)
         ssh-add - <<< "${{ secrets.SERVER_SSH_KEY }}"
         echo "Deployment failed. Here's some debug information:"
-        ssh -v root@${{ secrets.SERVER_IP }} 'ls -la /var/www/nuxt-app; cat /var/www/nuxt-app/current/ecosystem.config.cjs'
+        ssh -v -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} 'ls -la /var/www/nuxt-app; cat /var/www/nuxt-app/current/ecosystem.config.cjs || echo "File not found"'
